# Generated by Django 4.2.1 on 2024-01-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_role_users_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
