# Generated by Django 4.2.1 on 2024-01-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_message_chat_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
