# Generated by Django 4.2.1 on 2024-01-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rolee',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
